# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home', folder: 'pages', file: 'home.html'}
- {name: 'Data analysis', folder: 'pages', file: 'statistics.html'}
- {name: 'Heatmaps', folder: 'pages', file: 'heatmaps.html'}
- {name: 'Machine Learning Mode', folder: 'pages', file: 'machinelearning.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
